Prompt4Overconsistency = """

<instructions>
            ### Task Description:
            You are now an Video Evaluation Expert in evaluating generated videos.
            During the evaluation, you must strictly adhere to 'Evaluation Criteria'.

            ### Evaluation Criteria:
            You need to evaluate the overall consistency between the video and the text prompt. Overall consistency refers to how well the video content and style match the provided text prompt. 
            When evaluating this metric, consider the following:
            1. What are the core elements included in a text prompt? (Core elements include objects, actions, scenes, numerical relationships, styles, etc.)
            2. Whether the video is missing core elements from the text prompt, or if it has generated similar but imperfect elements, or if it has generated completely incorrect elements.

            ### Scoring Range
            You need to assign a specific score from 1 to 5 for each video(from 1 to 5, with 5 being the highest quality,using increments of 1) based strictly on the 'Evaluation Criteria':
            1. Very poor consistency (score=1)- All core elements are missing or generated incorrectly.
            2. Poor consistency (score=2)- Most core elements are missing or generated incorrectly, with two or more core elements absent.
            3. Moderate consistency (score=3)- Some core elements are missing or generated incorrectly, such as an missing action, an incorrect or missing object, or an incorrect number of objects.
            4. Good consistency (score=4)- All core elements are present and correctly generated, but some elements are not fully generated. For example, actions are present but not obvious, or actions are similar but not accurate enough, and the objects only roughly meets the requirements.
            5. Excellent consistency (score=5)- The video perfectly matches the text prompt. All core elements are generated correctly and fully, actions in the video are correct and obvious, and objects are accurate and clear.
            
            Notes for scoring to emphasize:
            1.Insufficient generation refers to the elements being generated but not meeting the requirements for consistency, such as low visibility in motion, or objects not conforming to the appearance of the objective world.
            2.All videos will be input at a rate of 2 frames per second. Please consider the duration of the motion when evaluating the amplitude and dynamics of motion (such as translation, rotation).
            3.This metric does not have high requirements for the video's visual quality.Excellent visual quality is not a necessary condition for a high score.


            ### Evaluation Steps:
            Follow the following steps strictly while giving the response:
            1. Carefully read the 'Evaluation Criteria' and 'Scoring Range'. You will need to review the text prompt and watch the videos with these criteria in mind.
            2. Read the text prompt carefully, noting all core elements mentioned, including objects, actions, styles, etc.
            3. Watch the frames of videos generated by different models and analyze them in conjunction with the evaluation criteria and text prompt.
            4. Analyze and evaluate the consistency of each video with the text prompt based on the evaluation criteria. Score each video according to the 'Scoring Range'.
            5. Display the results in the specified 'Output Format'.

</instructions>
"""


Prompt4Color = """
<instructions>
            ### Task Description:
            You are now an Video Evaluation Expert in evaluating generated videos.
            During the evaluation, you must strictly adhere to 'Evaluation Criteria' .

            ### Evaluation Criteria:
            You will evaluate the color consistency between the video and the text prompt. 
            Color consistency involves:
            1. **Overall Consistency**: Whether the color is consistent with the text prompt and remain consistent throughout the entire video and there are no abrupt changes in color.
            2. **Correct Allocation**: Whether the color is on the right object or background.

            ###Important Notes:
            And you should also pay attention to the following notes:
            1.The watermark in the video should not be a negative factor in the evaluation.
            2.The style of the video should not be a negative factor in the evaluation.            

            ### Scoring Range
            Then based on the above considerations, you need to assign a specific score from 1 to 3 for each video(from 1 to 3, with 3 being the highest quality,using increments of 1) according to the 'Scoring Range':

            1. Poor consistency - The generated object is incorrect or cannot be recognized or the color on the object does not match the text prompt at all.(e.g., yellow instead of red).
            2. Moderate consistency - The correct color appears in the video, but it's not perfect. The specific conditions are:
                -Condition 1: Incorrect allocation (e.g., color on the background, not the object).
                -Condition 2: Instability (e.g., sudden color changes).
                -Condition 3: Confusion (e.g., part of the object has the right color, but it's not dominant).
                -Condition 4: Blending (e.g., object color merging with the background).
                -Condition 5: Similarity (e.g., pink instead of purple).
            3.  Good consistency  - The color is highly consistent with the text prompt, the color in the entire video is stable, the color distribution is correct, there are no sudden changes or inconsistencies in color, and there are no issues mentioned in the moderate consistency category.


            ### Evaluation Steps
            1. **Understand the Task**:
            - Familiarize yourself with the purpose of the evaluation: to assess the aesthetic quality of generated videos based on the given criteria.
            2. **Review the Video**:
            - Watch the video carefully, focusing on visual elements and overall artistic merit.
            3. **Evaluate Overall Consistency**:
            - Evaluate whether the arrangement of people or objects is reasonable and pleasing, avoiding any psychological discomfort.
            4. **Evaluate Correct Allocation**:
            - Analyze the appropriateness and effectiveness of color choices, noting any discordant colors.
            5. **Assign a Score**:
            - Based on your evaluation, assign a score from 1 to 3 for each video according to the 'Scoring Range'.
            6. **Provide Justification**:
            - After assigning a score, explain your reasoning with specific examples from the video that influenced your decision.
            7. **Document the Evaluation**:
            - Use the 'Output Format' to document your evaluation.

</instructions>
"""


Prompt4Object_class = """
<instructions>
            ### Task Description:
            You are now an Video Evaluation Expert in evaluating generated videos.
            During the evaluation, you must strictly adhere to 'Evaluation Criteria'.

            ### Evaluation Criteria:
            You are required to evaluate the object class consistency between the video and the text prompt. Don't think about quantity consistency.
            Object class consistency refers to the consistency in object between the video and the provided text prompt.
            About how to evaluate this metric,after you watching the frames of videos,you should first consider the following:
            1.Whether the objects mentioned in the text were correctly and clearly generated.
            2.Whether the video focuses on only a part of the object.
            3.Whether the appearance and structure of the generated objects conform to objective reality and human subjective cognition.

            
            ###Important Notes:
            And you should also pay attention to the following notes:
            1.Focus solely on the object's consistency; disregard any considerations related to quantity consistency.
            2.If the video focuses on only a part of the object, it should be considered Moderate consistency.
            

            ### Scoring Range
            Then based on the above considerations, you need to assign a specific score from 1 to 3 for each video(from 1 to 3, with 3 being the highest quality,using increments of 1) according to the 'Scoring Range':

            1. Poor consistency (score=1)- Completely unrecognizable as the specified object.The object is not discernible at all.
            2. Moderate consistency (score=2)- The object can barely be recognized or is generated imperfectly.The specific conditions are:
                - Condition 1 : A similar object with a related function or structure is generated, (e.g., a "snowboard" instead of "skis", a “unicycle” instead of a “bicycle,”)
                - Condition 2 : The object cannot be accurately recognized, (e.g. Uncertain words such as "appears to, seemingly" appear in the video description).
                - Condition 3 : The object in the video is blurred and inconspicuous, making it difficult to recognize.
                - Condition 4 : The video focuses on only a part of the object. (e.g. generating a human hand instead of a whole person.)
                - Condition 5 : More than 3 frames in the video are missing the object.
                - Condition 6 : The appearance of the object changes significantly. (e.g., a person sometimes has facial features and sometimes does not.)
            3. Good consistency (score=3)- The object category is consistently correct throughout the video, the object is complete, clear, obvious, and remains visible in the video and there are no issues mentioned in the moderate consistency category.


"""


Prompt4Scene = """
<instructions>
        ### Task Description:
        You are a Video Evaluation Expert tasked with evaluating the scene generation capabilities of AI-generated videos. 
        Your evaluation should be based solely on the provided "Evaluation Criteria" and 'Evaluation Steps'.
        Each video should be assessed independently, without comparisons to others.

        ### Evaluation Criteria:
        You will assess the scene consistency between each video and the corresponding text prompt.
        Scene consistency involves:
        1. **Recognizability**: Can the scene described in the text be identified in the video?  
        2. **Realism**: Do the elements within the scene align with objective reality and human cognitive understanding?

        ### Important Notes:
        1. Watermarks in the video should not negatively impact your evaluation.  
        2. Acceptable video quality includes some blur or distortion as long as scene recognition is not compromised.  
        3. The style of the video should not be a negative factor in the evaluation.

        ### Scoring Range
        Then based on the above considerations, you need to assign a specific score from 1 to 3 for each video(from 1 to 3, with 3 being the highest quality,using increments of 1) according to the 'Scoring Range':

        1. Poor consistency - The generated object is incorrect or cannot be recognized or the color on the object does not match the text prompt at all.(e.g., yellow instead of red).
        2. Moderate consistency - The scene is barely recognizable or imperfectly generated, meeting one or more of the following conditions:
            - Condition 1 : The scene lacks the most typical features (e.g., a bathroom without a shower).
            - Condition 2 : Only a close-up of an object within the scene is shown, with a very limited perspective (e.g., only a close-up of a single loaf of bread in a bakery).
            - Condition 3 : The scene is too vague or overly broad in perspective, lacking specific identifiers (e.g., a hospital is represented by just a building with no clear signage instead of the interior of a hospital).
            - Condition 4 : The scene resembles the text prompt but lacks accuracy (e.g., an aquarium without a glass enclosure).
            - Condition 5 : The scene abruptly shifts to a different, less fitting scene, without consistently showing the primary characteristics of the scene (e.g., a football field shifts to a close-up of a football player).
        3.  Good consistency  - The scene in the video perfectly matches the text prompt, displaying typical and expected features.



</instructions>
"""


Prompt4Action = """
<instructions>
        ### Task Description:
        You are a Video Evaluation Expert tasked with evaluating the action generation capabilities of AI-generated videos. 
        Your evaluation should be based solely on the provided "Evaluation Criteria" and 'Evaluation Steps'. 
        Each video should be assessed independently, without comparisons to others.

        ### Evaluation Criteria:
        You will assess the action consistency between each video and the corresponding text prompt.
        Action consistency involves:
        1. **Recognizability**: Can the action described in the text be identified in the video?
        2. **Realism**: Do the appearance and process of the actions align with objective reality and human understanding?  
    
        ###Important Notes:
        And you should also pay attention to the following notes:
        1. You only need to pay attention to the action of the subject in the video, not the number of subjects.
        2. If the text prompt contains multiple actions, determine whether the subject in the video has completed all of them.
        3. The style of the video should not be a negative factor in the evaluation.


        ### Scoring Range
        Then based on the above considerations, you need to assign a specific score from 1 to 3 for each video(from 1 to 3, with 3 being the highest quality,using increments of 1) according to the 'Scoring Range':

        1. Poor consistency - The subject's action does not match the text prompt at all, or the subject's action is not recognized, or the subject in the text prompt does not appear.
        2. Moderate consistency - The main subject’s action is barely recognizable but imperfectly generated, specifically meeting one or more of the following conditions:
            - Condition 1 : The main subject's action is incomplete and does not fully perform the action in the text prompt.
            - Condition 2 : The main subject’s action has significant deviations in appearance or process compared to the real action, making it distorted and hard to recognize.
            - Condition 3 : The subject's action changes into another action that is inconsistent with the action in the text prompt.
            - Condition 4 : A similar action is generated, such as marching instead of parading.
            - Condition 5 : The subject in the video did not complete all of the actions in the text prompt, but only partially completed them
        3.  Good consistency  - The action fully aligns with the text prompt, is accurate, complete, and clearly recognizable, without any abrupt changes in the action.
                

        ### Evaluation Steps

        1. **Understand the Task**:
        - Familiarize yourself with the evaluation's purpose: to assess the action generation capabilities of AI-generated videos based on the provided criteria.

        2. **Review the Video and Text Prompt**:
        - Carefully watch the video.
        - Read the corresponding text prompt to understand the intended actions.

        3. **Assess Recognizability**:
        - Determine if the action described in the text is clearly identifiable in the video.
        - Ask yourself: Does the video accurately represent the action mentioned in the prompt?

        4. **Evaluate Realism**:
        - Analyze the appearance and process of the actions. Do they align with objective reality and human understanding?
        - Consider whether the actions appear plausible and reasonable within the context.

        5. **Consider Important Notes**:
        - Watermarks should not negatively affect your evaluation.
        - Accept some degree of blur or distortion, as long as it does not hinder action recognition.
        - Focus on action consistency; do not evaluate dynamic performance or motion effects.

        6. **Assign a Score**:
        - Based on your assessment, assign a score from 1 to 3 for each video according to the 'Scoring Range'.

        7. **Provide Justification**:
        - After assigning a score, clearly explain your reasoning.
        - Include specific examples from the video that led to your conclusion about the score.

        8. **Document the Evaluation**:
        - Use the 'Output Format' to document your evaluation.




</instructions>
"""

Prompt4ImagingQuality = """
<instructions>
        ### Task Description:
        You are now an Video Evaluation Expert in evaluating generated videos and need to evaluate the videos from different models.
        During the evaluation, you must strictly adhere to 'Evaluation Criteria'.and 'Evaluation Steps'.

        ### Evaluation Criteria:
        You will evaluate the image quality of each video, focusing on low-level distortions present in the frames. 
        Image quality involves:
        1. **Clarity**: Evaluate the clarity of the video, as this is the most critical factor in image quality.
        2. **Noise**: Evaluate the presence and level of noise in the video.
        3. **Brightness**: Evaluate whether the brightness is reasonable and determine the extent of any overexposure.

   
        ### Scoring Range:
        Assign a score from 1 to 5 for each video, with 5 representing the highest quality, based on the 'Evaluation Criteria':
        1. **Very Poor Quality (score=1)**: Significant distortion, severe blurriness, numerous noise spots, excessive brightness, resulting in a very poor viewing experience.
        2. **Poor Quality (score=2)**: Noticeable distortions, blurriness, and interference from noise spots, leading to an unnatural viewing experience.
        3. **Moderate Quality (score=3)**: Clarity meets standard definition, with minor distortions, some noise spots, and slight overexposure, resulting in an average experience.
        4. **Good Quality (score=4)**: Clarity reaches high definition, with very few distortions, providing a good viewing experience.
        5. **Excellent Quality (score=5)**: Clarity is at full high definition, with no distortions, delivering an excellent viewing experience.

"""

Prompt4AestheticQuality = """
<instructions>
        ### Task Description:
        You are a Video Evaluation Expert tasked with evaluating the image quality of generated videos. 
        Your evaluation should be based solely on the provided "Evaluation Criteria" and 'Evaluation Steps'.
        Each video should be evaluated independently, without comparisons to others.
        ### Evaluation Criteria:
        You are required to evaluate the aesthetic quality of the videos, which refers to the visual appeal and artistic merit of the footage.
        Aesthetic quality involves:
        1. **Structure**: Evaluate if the arrangement of people or objects is reasonable and pleasing, avoiding psychological discomfort.
        2. **Color Use**: Evaluate the appropriateness of color choices in the video.
        3. **Composition**: Determine if the composition effectively presents all necessary information.
        4. **Visual Appeal**: Evaluate the video's overall visual appeal and emotional expression.
        5. **Harmony**: Evaluate whether the video feels cohesive and harmonious as a whole.

        ### Scoring Range:
        Assign a score from 1 to 5 for each video based strictly on the 'Evaluation Criteria', with 5 representing the highest quality:
        1. **Very Poor Quality (score=1)**: Significant issues in color, composition, and clarity; lacks visual appeal and emotional expression; overall harmony is poor.
        2. **Poor Quality (score=2)**: Noticeable problems in specific aspects, such as discordant colors or poor composition, negatively affecting the overall aesthetic experience.
        3. **Moderate Quality (score=3)**: Average performance in most aspects; may have minor deficiencies, but provides a basic aesthetic experience.
        4. **Good Quality (score=4)**: Strong performance in color, composition, and clarity; offers a visually satisfying experience with reasonable emotional expression and creativity.
        5. **Excellent Quality (score=5)**: Excels in all aspects, with high standards in color, composition, and clarity; delivers strong visual impact and profound emotional expression, resulting in an outstanding aesthetic experience.

        ### Important Notes:
        In the evaluation, you will get example frames from other model and the frames from the video to be evaluted.
        The frames from the video to be evaluated are provided after the example frames. 
        You should evaluate all input frames but just need to provide the score for the video to be evaluated. 
"""



Prompt4Motioneffects="""
<instructions>
            ### Task Description:
            You are now an Video Evaluation Expert in evaluating generated videos.
            During the evaluation, you must strictly adhere to 'Evaluation Criteria'.

            ### Evaluation Criteria:
            You are required to evaluate the motion effects of actions in videos.
            Motion effects refer to the naturalness, coherence, and realism of object movement in a video. This metric primarily assesses whether the dynamic effects displayed in the video conform to actual physical laws and human visual perception.
            About how to evaluate this metric,onsider the following:
                1.Whether the motion trajectories of objects are consistent with physical laws, such as inertia and gravity.
                2.Whether the dynamic blur associated with the motion of objects is coherent with the speed and direction of the movement.
                3.Whether the relationship between moving objects and their background is coherent, including occlusions and reflections that align with real-world expectations.
                4.Whether the changes in shadows and lighting as objects move are consistent with physical laws, enhancing the realism of the scene.
        
            ### Important Notes:
            1.The evaluation of motion effects does not need to care the action consistency too much. The focus is on whether the motion effects of actions in the video conform to actual physical laws and human visual perception.
            2.Image quality is not the focus of this evaluation. You should focus on the motion effects of the objects in the video.

            ###Scoring Range
            You need to assign a specific score from 1 to 5 for each video (from 1 to 5, with 5 being the highest quality, using increments of 1) based strictly on the 'Evaluation Criteria':
            1: Very poor effects - The motion trajectories are significantly incorrect.There is a clear violation of physical laws, and the dynamic blur is either absent or does not correspond with the motion at all.
            2: Poor effects - The motion trajectories are generated poorly, and the motion is barely dynamic. The dynamic blur is inconsistent with the speed and direction of the movement, and there are noticeable issues with the coherence of the object's interaction with the background and lighting.
            3: Moderate effects - The motion effects are generally present, and the movement can be recognized, but there is one of the following issues:
                The motion smoothness is compromised, with noticeable frame-to-frame inconsistencies or abrupt changes that disrupt the flow of the movement.
                The motion blur is either underutilized or overused, not accurately reflecting the speed and direction of the movement, which affects the perception of realism.
                The motion consistency is partially maintained, but certain elements, such as the interaction between moving objects and their environment or the changes in shadows and lighting, are not fully convincing or are inconsistently portrayed.
                The motion is not dynamic enough, lacking the sense of speed and direction that would enhance the realism of the scene.
            4: Good effects - The action can be recognized and the motion trajectories and dynamic blur are mostly coherent,but there are some parts of the motion is unnatural and does not conform to the human subjective understanding of changes in the objective world.
            5: Excellent effects - The action can be clearly recognized, and the motion trajectories are accurate, dynamic blur is appropriately applied, and the interaction of moving objects with their environment, including shadows and lighting, is seamlessly integrated and realistic.
           

            ### The Output Format:
            Finally for the evaluation results, you should assign a score to each video and provide the reason behind the scores.
            Assuming there are 1 video input from model 'A' scoring 'x',the format is:
            <output format>
            Final Scores:
            - A: x ,because ...
            </output format>
                
            <example>
            Assuming there are 1 video input from model 'gen2' scoring '3',the format is:
            Final Scores:
            - gen2: 3 , because ...
            </example>

            ### Evaluation Steps:
            Follow the following steps strictly while giving the response:
            1. Carefully read the 'Evaluation Criteria' and 'Scoring Range'. You will need to review the text prompt and watch the videos with these criteria in mind.
            2. Read the text prompt carefully,noting the scene mentioned in the text prompt.
            3. Watch the frames of videos generated by different models and analyze them in conjunction with the evaluation criteria and text prompt.
            4. Compare the differences between consecutive frames to understand the action process in the video.
            5. Analyze and evaluate the consistency of each video with the text prompt based on the evaluation criteria and think about the questions below step by step and then Score each video according to the 'Scoring Range':
                Whether the motion trajectories of objects are consistent with physical laws, such as inertia and gravity.
                Whether the dynamic blur associated with the motion of objects is coherent with the speed and direction of the movement.
                Whether the relationship between moving objects and their background is coherent, including occlusions and reflections that align with real-world expectations.
                Whether the changes in shadows and lighting as objects move are consistent with physical laws, enhancing the realism of the scene.
            6. Display the results in the specified 'Output Format'.

</instructions>
"""

extra_motion="""
                

            ### The Output Format:
            Finally for the evaluation results, you should assign a score to each video and provide the reason behind the scores.
            Assuming there are 1 video input from model 'A' scoring 'x',the format is:
            <output format>
            Final Scores:
            - A: x ,because ...
            </output format>
                
            <example>
            Assuming there are 1 video input from model 'gen2' scoring '3',the format is:
            Final Scores:
            - gen2: 3 , because ...
            </example>

            ### Evaluation Steps:
            Follow the following steps strictly while giving the response:
            1. Carefully read the 'Evaluation Criteria' and 'Scoring Range'. You will need to review the text prompt and watch the videos with these criteria in mind.
            2. Read the text prompt carefully,noting the scene mentioned in the text prompt.
            3. Watch the frames of videos generated by different models and analyze them in conjunction with the evaluation criteria and text prompt.
            4. Compare the differences between consecutive frames to understand the action process in the video.
            5. Analyze and evaluate the consistency of each video with the text prompt based on the evaluation criteria and think about the questions below step by step and then Score each video according to the 'Scoring Range':
                Whether the motion trajectories of objects are consistent with physical laws, such as inertia and gravity.
                Whether the dynamic blur associated with the motion of objects is coherent with the speed and direction of the movement.
                Whether the relationship between moving objects and their background is coherent, including occlusions and reflections that align with real-world expectations.
                Whether the changes in shadows and lighting as objects move are consistent with physical laws, enhancing the realism of the scene.
            6. Display the results in the specified 'Output Format'."""

Prompt4TemperalConsistency="""
<instructions>
            ### Task Description:
            You are now an Video Evaluation Expert in evaluating generated videos and have super power to perceive the changes between frames.
            During the evaluation, you must strictly adhere to 'Evaluation Criteria' .

            ### Evaluation Criteria:
            You will evaluate the temporal consistency between the video and the text prompt. 
            Temporal consistency is to measure **frame-to-frame** coherence in the video, focusing on the smoothness and stability of visual and semantic features across consecutive frames.
            The visual features includes color, brightness, texture and details.
            The semantic features  includes object class,positions, shapes, and scene layout.
            To evaluate this metric, you should focus on the following aspects:
                1.whether the frame flickering in the video is noticeable.
                2.Whether the 2 kinds of features of the primary object changes unnaturally between consecutive frames.
                3.Whether the 2 kinds of features of the unimportant objects or background changes unnaturally between consecutive frames.
                
            ###Important Notes:
            And you should also pay attention to the following notes:
            1.The watermark in the video should not be a negative factor in the evaluation.
            2.The style of the video should not be a negative factor in the evaluation.            

            ### Scoring Range
            Then based on the above considerations, you need to assign a specific score from 1 to 5 for each video(from 1 to 5, with 5 being the highest quality,using increments of 1) according to the 'Scoring Range':
            1: Very poor consistency - The video content can be understood, but there are noticeable unnatural changes in the primary object in the video, significantly affecting the overall temporal consistency. 
            2: Poor consistency - The video content can be understood, but there are noticeable inconsistencies or unnatural changes in unimportant objects, which affect the overall coherence.
            3: Moderate consistency - The video content is fully presented but there are noticeable inconsistencies or unnatural changes in background which slightly affect the overall coherence.
            4: Good consistency - The video is complete and comprehensive without noticeable unnatural changes but there are texture flickering or color jitter in the visual features of background.
            5: Excellent consistency -  The video provides a full expression of the content and all visual and semantic features are consistent between consecutive frames, and there are no noticeable frame flickering in the video.


</instructions>
"""
Prompt4TemperalConsistency_test="""
<instructions>
            ### Task Description:
            You are now an Video Evaluation Expert in evaluating generated videos and have super power to perceive the changes between frames.
            During the evaluation, you must strictly adhere to 'Evaluation Criteria'.

            ### Evaluation Criteria:
            You will evaluate the temporal consistency between the video and the text prompt. 
            Temporal consistency is to measure **frame-to-frame** coherence in the video, focusing on the smoothness and stability of visual and semantic features across consecutive frames.
            The visual features includes color, brightness, texture and details.
            The semantic features  includes object class,positions, shapes, and scene layout.
            To evaluate this metric, you should focus on the following aspects:
                1.Whether the 2 kinds of features of the primary object changes unnaturally between consecutive frames.
                3.Whether the 2 kinds of features of the unimportant objects or background changes unnaturally between consecutive frames.
                3.whether the frame flickering in the video is noticeable.

            ###Important Notes:
            And you should also pay attention to the following notes:
            1.Unnatural changes refer to changes that are inconsistent with the laws of physics or human visual perception, such as
              -sudden shifts in color, texture, or position.
              -objects appearing or disappearing abruptly.
              -objects turning into other objects.
              -sudden changes in lighting or shadows.
              -sudden changes in the background or scene layout.
            2.The metric is a sensitive metric, you need to pay attention to the changes between frames.
            3.The minor unnatural changes in the video even matters if it is noticable for human eyes. 

            ### Scoring Range
            Then based on the above considerations, you need to assign a specific score from 1 to 5 for each video(from 1 to 5, with 5 being the highest quality,using increments of 1) according to the 'Scoring Range':
            1: Very poor consistency - There are many  unnatural changes through the whole video.
            2: Poor consistency -  There are noticeable unnatural changes in the primary object in the video, affecting the overall temporal consistency. 
            3: Moderate consistency - The video content is fully presented but there are noticeable unnatural changes in unimportant objects or background, which do not significantly affect the overall coherence.
            4: Good consistency - The video is complete and comprehensive with minor unnatural changes and there are noticeable frame flickering in the visual features.
            5: Excellent consistency -  The video provides a full expression of the content and all visual and semantic features are consistent between consecutive frames, and there are no noticeable frame flickering in the video.


</instructions>
"""